// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASChoZrwpK6781Q5wkb7cEYA_0tWWwKYU',
    appId: '1:847341799623:android:d17fbc94692a011c5156e2',
    messagingSenderId: '847341799623',
    projectId: 'givt-dev-pre',
    databaseURL: 'https://givt-dev-pre.firebaseio.com',
    storageBucket: 'givt-dev-pre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZGVYKOk1Iy1OYWSZgT4yqCmLpvLH9f4I',
    appId: '1:847341799623:ios:dbf419704881d64d5156e2',
    messagingSenderId: '847341799623',
    projectId: 'givt-dev-pre',
    databaseURL: 'https://givt-dev-pre.firebaseio.com',
    storageBucket: 'givt-dev-pre.appspot.com',
    iosClientId: '847341799623-17r22pgkoe6j648jiag3c2hvpurt3i7m.apps.googleusercontent.com',
    iosBundleId: 'net.givtapp.ios.test',
  );
}
