source "https://rubygems.org"

gem "fastlane", '~> 2.217.0'
gem "cocoapods"
gem 'fastlane-plugin-flutter_version', '~> 1.0', '>= 1.1.14'

# remove file when fastlane issue is solved
# https://github.com/fastlane/fastlane/issues/21762 