# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  git_url = "git@github.com:givtnl/givt.apps.codesigning.git"
  # Lane used to setup fastlane match https://codesigning.guide/
  lane :certificates do
    match(type: "appstore", app_identifier: "net.givtapp.ios", git_url: git_url, force: true)
    match(type: "appstore", app_identifier: "net.givtapp.ios.test", git_url: git_url, force: true)
  end

  desc "Push a new build to Testflight"
  lane :release do
    flavor = ENV['FLAVOR']
    app_identifier = ENV['APP_IDENTIFIER']
    logit_api_key = ENV['LOGIT_API_KEY']
    api_url_us= ENV['API_URL_US']
    api_url_eu= ENV['API_URL_EU']
    api_url_aws_eu= ENV['API_URL_AWS_EU']
    api_url_aws_us= ENV['API_URL_AWS_US']
    amplitude_key= ENV['AMPLITUDE_KEY']
    setup_ci
    sync_code_signing(type: "appstore", readonly: true, app_identifier: app_identifier, git_url: git_url)
    api_key = app_store_connect_api_key(
        key_id: "98V29B2SCY",
        issuer_id: "69a6de8f-dee3-47e3-e053-5b8c7c11a4d1",
        key_content: ENV['APPSTORECONNECT_PRIVATE_KEY']
    )
    build_number = latest_testflight_build_number(api_key: api_key, app_identifier: app_identifier) + 1
    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "ipa", "--flavor", flavor, 
          "--target", "lib/main_#{flavor}.dart", 
          "--build-number=#{build_number}", 
          "--dart-define=LOGIT_API_KEY=#{logit_api_key}",
          "--dart-define=API_URL_US=#{api_url_us}",
          "--dart-define=API_URL_EU=#{api_url_eu}",
          "--dart-define=API_URL_AWS_EU=#{api_url_aws_eu}",
          "--dart-define=API_URL_AWS_US=#{api_url_aws_us}",
          "--dart-define=AMPLITUDE_KEY=#{amplitude_key}",
        )
    end
    build_app(
      scheme: flavor, 
      skip_build_archive: true, 
      include_symbols: true, 
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )
    dsym_zip
    upload_to_testflight(
      app_identifier: app_identifier,
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
