name: example
description: "Example app for waveform_flutter"
version: 1.2.0
repository: https://github.com/agenthesh/waveform
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  waveform_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
