# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload keystore"
  lane :keystore do
    match_keystore(git_url: "git@github.com:givtnl/givt.apps.codesigning.git", package_name: "net.givtapp.droid2", override_keystore: true)
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :build_and_deploy do
    flavor = ENV['FLAVOR']
    package_name = ENV['PACKAGE_NAME']
    track = ENV['TRACK']
    logit_api_key = ENV['LOGIT_API_KEY']
    api_url_us = ENV['API_URL_US']
    api_url_eu = ENV['API_URL_EU']
    api_url_aws_eu = ENV['API_URL_AWS_EU']
    api_url_aws_us = ENV['API_URL_AWS_US']
    amplitude_key = ENV['AMPLITUDE_KEY']
    stripe_pk = ENV['STRIPE_PK']
    stripe_merchant_id = ENV['STRIPE_MERCHANT_ID']
    build_number = google_play_track_version_codes(package_name: package_name, track: 'production', json_key_data: ENV['GOOGLE_PLAY_JSON_KEY'])[0] + 1

    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "appbundle", "--flavor", flavor, 
          "--target", "lib/main_#{flavor}.dart", 
          "--build-number=#{build_number}", 
          "--dart-define=LOGIT_API_KEY=#{logit_api_key}",
          "--dart-define=API_URL_US=#{api_url_us}",
          "--dart-define=API_URL_EU=#{api_url_eu}",
          "--dart-define=API_URL_AWS_EU=#{api_url_aws_eu}",
          "--dart-define=API_URL_AWS_US=#{api_url_aws_us}",
          "--dart-define=AMPLITUDE_KEY=#{amplitude_key}",
          "--dart-define=STRIPE_PK=#{stripe_pk}",
          "--dart-define=STRIPE_MERCHANT_ID=#{stripe_merchant_id}"
        )
    end
    signed_aab_path = match_keystore(git_url: "git@github.com:givtnl/givt.apps.codesigning.git", 
                    package_name: package_name,
                    aab_path: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
                    match_secret: ENV['MATCH_PASSWORD'],
                    override_keystore: false)
    upload_to_play_store(
                        package_name: package_name,
                        json_key_data: ENV['GOOGLE_PLAY_JSON_KEY'], 
                        aab: signed_aab_path,
                        release_status: "completed",
                        track: track)
  end
end
